"""'initial'

Revision ID: 0731036068d6
Revises: 
Create Date: 2025-03-21 09:34:02.213771

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0731036068d6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('animal_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('animal', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_animal_type_animal'), 'animal_type', ['animal'], unique=True)
    op.create_index(op.f('ix_animal_type_id'), 'animal_type', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('time', sa.Time(), nullable=False),
    sa.Column('owner', sa.String(), nullable=False),
    sa.Column('pet', sa.Integer(), nullable=False),
    sa.Column('pet_name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['pet'], ['animal_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_date'), 'report', ['date'], unique=False)
    op.create_index(op.f('ix_report_id'), 'report', ['id'], unique=False)
    op.create_index(op.f('ix_report_owner'), 'report', ['owner'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_report_owner'), table_name='report')
    op.drop_index(op.f('ix_report_id'), table_name='report')
    op.drop_index(op.f('ix_report_date'), table_name='report')
    op.drop_table('report')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_animal_type_id'), table_name='animal_type')
    op.drop_index(op.f('ix_animal_type_animal'), table_name='animal_type')
    op.drop_table('animal_type')
    # ### end Alembic commands ###
